# ansible/playbook.yml
- name: Configure Minecraft Server
  hosts: all
  become: yes
  tasks:
    - name: Import Amazon Corretto GPG key
      rpm_key:
        key: https://yum.corretto.aws/corretto.key
        state: present

    - name: Add Amazon Corretto yum repository
      yum_repository:
        name: corretto
        description: Amazon Corretto
        baseurl: https://yum.corretto.aws/corretto.repo
        gpgcheck: yes
        gpgkey: https://yum.corretto.aws/corretto.key
        enabled: yes

    - name: Install Java 21 (Amazon Corretto)
      yum:
        name: java-21-amazon-corretto-devel
        state: present

    - name: Create Minecraft user
      user:
        name: minecraft
        shell: /bin/bash
        create_home: yes

    - name: Create Minecraft directory
      file:
        path: /home/minecraft
        state: directory
        owner: minecraft
        group: minecraft
        mode: '0755'

    - name: Download Minecraft Server
      get_url:
        url: https://piston-data.mojang.com/v1/objects/59353fb40c36d304f2035d51e7d6e6baa98dc05c/server.jar
        dest: /home/minecraft/server.jar
        owner: minecraft
        group: minecraft
        mode: '0644'
      notify: Restart Minecraft

    - name: Accept EULA
      copy:
        content: "eula=true\n"
        dest: /home/minecraft/eula.txt
        owner: minecraft
        group: minecraft
        mode: '0644'

    - name: Setup Systemd Service
      template:
        src: templates/minecraft.service.j2
        dest: /etc/systemd/system/minecraft.service
        owner: root
        group: root
        mode: '0644'
      notify: Restart Minecraft

  handlers:
    - name: Restart Minecraft
      systemd:
        name: minecraft
        state: restarted
        enabled: yes
        daemon_reload: yes